### ISSUE TITLE
Experiment Results

### ISSUE THREAD

**Issue by MrChenFeng** [MalteEbner/NNCLR#2]
Hi,

Thanks for open source your codes.
Do you have any experiment results on cifar?
In my implementation I found there are no advantages or nnclr compared to simclr if controlled in same settings.

Best,
Chen

**Comment by MalteEbner** [comment]
Hi Chen,

for direct comparisons, it might be best to use the original paper: https://arxiv.org/pdf/2104.14548.pdf


For more benchmarks, best head to the lightly package for self-supervised learning, it supports much more models and benchmarks:
https://docs.lightly.ai/getting_started/benchmarks.html#cifar10
The code from this repository was merged into the lightly package, you find an implementation of NNCLR for an imagenette benchmark here: https://github.com/lightly-ai/lightly/blob/57ec16a13adf32fd74551079a3a0a5f4e969ae4f/docs/source/getting_started/benchmarks/imagenette_benchmark.py#L243-L290
It also includes a benchmark of NNCLR, SimCLR and other models on Imagenette.

Unfortunately we have not run any benchmarks of our implementation of NNCLR on CIFAR10 yet. If you want to, you can add your results via a PR. We welcome any contributions!

Best, Malte

**Comment by MalteEbner** [comment]
@MrChenFeng 
Do you have further questions? If not, I would like to close this issue.

**Comment by MrChenFeng** [comment]
Hi Matle,

sorry for the late reply. Thanks so much. I think it's okay to close the issue now!

Best,
Chen
