### ISSUE TITLE
Run code error

### ISSUE THREAD

**Issue by skr998** [MalteEbner/NNCLR#3]
Hi, 

thanks for your code, but there is a error when running it,
![image](https://user-images.githubusercontent.com/77918488/158773513-676799d7-040b-41a8-a5ed-46884b7048e4.png)

Is this code completely correct and can it be run?

**Comment by skr998** [comment]
Moreover,

import pytorch_lightning as pl
import lightly

What are the specific versions of these packages?

**Comment by MalteEbner** [comment]
Hello @skr998 

this repository has been incorporated into the Lightly repository and is not maintained anymore. Please try to use the NNCLR model there: https://docs.lightly.ai/examples/nnclr.html

**Comment by skr998** [comment]
Thank you very much
